//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Hotfix.Bright.Serialization;
using System.Collections.Generic;



namespace Hotfix.Model
{

public sealed partial class Int2 :  Bright.Config.BeanBase 
{
    public Int2(ByteBuf _buf) 
    {
        I1 = _buf.ReadInt();
        I2 = _buf.ReadInt();
        PostInit();
    }

    public static Int2 DeserializeInt2(ByteBuf _buf)
    {
        return new Int2(_buf);
    }

    public int I1 { get; private set; }
    public int I2 { get; private set; }

    public const int __ID__ = 2284099;
    public override int GetTypeId() => __ID__;

    public  void Resolve(Dictionary<string, object> _tables)
    {
        PostResolve();
    }

    public  void TranslateText(System.Func<string, string, string> translator)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "I1:" + I1 + ","
        + "I2:" + I2 + ","
        + "}";
    }
    
    partial void PostInit();
    partial void PostResolve();
}

}
