//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Hotfix.Bright.Serialization;
using System.Threading.Tasks;


namespace Hotfix.Model
{
   
public partial class Tables
{
    public Put.TbArea TbArea {get; private set; }
    public Put.TbTask TbTask {get; private set; }
    public Put.TbStaff TbStaff {get; private set; }
    public Put.TbStaffLevelUp TbStaffLevelUp {get; private set; }
    public Put.TbItem TbItem {get; private set; }
    public Put.TbBuilding TbBuilding {get; private set; }
    public Put.TbSite TbSite {get; private set; }
    public Put.TbVehicle TbVehicle {get; private set; }
    public Put.TbDefaultSite TbDefaultSite {get; private set; }
    public Put.TbSkill TbSkill {get; private set; }
    public Put.TbManager TbManager {get; private set; }
    public SanXiao.TbBlockUnit TbBlockUnit {get; private set; }
    public SanXiao.TbSanXiaoSkill TbSanXiaoSkill {get; private set; }
    public SanXiao.TbHeroUnit TbHeroUnit {get; private set; }
    public SanXiao.TbSanXiaoLevel TbSanXiaoLevel {get; private set; }
    public SanXiao.TbLevelTheme TbLevelTheme {get; private set; }
    public SanXiao.TbSanXiaoBuff TbSanXiaoBuff {get; private set; }

    public Tables() { }

    public async Task LoadAsync(System.Func<string, Task<ByteBuf>> loader)
    {
        var tables = new System.Collections.Generic.Dictionary<string, object>();
        TbArea = new Put.TbArea(await loader("put_tbarea")); 
        tables.Add("Put.TbArea", TbArea);
        TbTask = new Put.TbTask(await loader("put_tbtask")); 
        tables.Add("Put.TbTask", TbTask);
        TbStaff = new Put.TbStaff(await loader("put_tbstaff")); 
        tables.Add("Put.TbStaff", TbStaff);
        TbStaffLevelUp = new Put.TbStaffLevelUp(await loader("put_tbstafflevelup")); 
        tables.Add("Put.TbStaffLevelUp", TbStaffLevelUp);
        TbItem = new Put.TbItem(await loader("put_tbitem")); 
        tables.Add("Put.TbItem", TbItem);
        TbBuilding = new Put.TbBuilding(await loader("put_tbbuilding")); 
        tables.Add("Put.TbBuilding", TbBuilding);
        TbSite = new Put.TbSite(await loader("put_tbsite")); 
        tables.Add("Put.TbSite", TbSite);
        TbVehicle = new Put.TbVehicle(await loader("put_tbvehicle")); 
        tables.Add("Put.TbVehicle", TbVehicle);
        TbDefaultSite = new Put.TbDefaultSite(await loader("put_tbdefaultsite")); 
        tables.Add("Put.TbDefaultSite", TbDefaultSite);
        TbSkill = new Put.TbSkill(await loader("put_tbskill")); 
        tables.Add("Put.TbSkill", TbSkill);
        TbManager = new Put.TbManager(await loader("put_tbmanager")); 
        tables.Add("Put.TbManager", TbManager);
        TbBlockUnit = new SanXiao.TbBlockUnit(await loader("sanxiao_tbblockunit")); 
        tables.Add("SanXiao.TbBlockUnit", TbBlockUnit);
        TbSanXiaoSkill = new SanXiao.TbSanXiaoSkill(await loader("sanxiao_tbsanxiaoskill")); 
        tables.Add("SanXiao.TbSanXiaoSkill", TbSanXiaoSkill);
        TbHeroUnit = new SanXiao.TbHeroUnit(await loader("sanxiao_tbherounit")); 
        tables.Add("SanXiao.TbHeroUnit", TbHeroUnit);
        TbSanXiaoLevel = new SanXiao.TbSanXiaoLevel(await loader("sanxiao_tbsanxiaolevel")); 
        tables.Add("SanXiao.TbSanXiaoLevel", TbSanXiaoLevel);
        TbLevelTheme = new SanXiao.TbLevelTheme(await loader("sanxiao_tbleveltheme")); 
        tables.Add("SanXiao.TbLevelTheme", TbLevelTheme);
        TbSanXiaoBuff = new SanXiao.TbSanXiaoBuff(await loader("sanxiao_tbsanxiaobuff")); 
        tables.Add("SanXiao.TbSanXiaoBuff", TbSanXiaoBuff);

        PostInit();
        TbArea.Resolve(tables); 
        TbTask.Resolve(tables); 
        TbStaff.Resolve(tables); 
        TbStaffLevelUp.Resolve(tables); 
        TbItem.Resolve(tables); 
        TbBuilding.Resolve(tables); 
        TbSite.Resolve(tables); 
        TbVehicle.Resolve(tables); 
        TbDefaultSite.Resolve(tables); 
        TbSkill.Resolve(tables); 
        TbManager.Resolve(tables); 
        TbBlockUnit.Resolve(tables); 
        TbSanXiaoSkill.Resolve(tables); 
        TbHeroUnit.Resolve(tables); 
        TbSanXiaoLevel.Resolve(tables); 
        TbLevelTheme.Resolve(tables); 
        TbSanXiaoBuff.Resolve(tables); 
        PostResolve();
    }

    public void TranslateText(System.Func<string, string, string> translator)
    {
        TbArea.TranslateText(translator); 
        TbTask.TranslateText(translator); 
        TbStaff.TranslateText(translator); 
        TbStaffLevelUp.TranslateText(translator); 
        TbItem.TranslateText(translator); 
        TbBuilding.TranslateText(translator); 
        TbSite.TranslateText(translator); 
        TbVehicle.TranslateText(translator); 
        TbDefaultSite.TranslateText(translator); 
        TbSkill.TranslateText(translator); 
        TbManager.TranslateText(translator); 
        TbBlockUnit.TranslateText(translator); 
        TbSanXiaoSkill.TranslateText(translator); 
        TbHeroUnit.TranslateText(translator); 
        TbSanXiaoLevel.TranslateText(translator); 
        TbLevelTheme.TranslateText(translator); 
        TbSanXiaoBuff.TranslateText(translator); 
    }
    
    partial void PostInit();
    partial void PostResolve();
}

}