//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Hotfix.Bright.Serialization;
using System.Collections.Generic;



namespace Hotfix.Model.Put
{

public sealed partial class DRArea :  Bright.Config.BeanBase 
{
    public DRArea(ByteBuf _buf) 
    {
        Id = _buf.ReadInt();
        Name = _buf.ReadString();
        SceneId = _buf.ReadInt();
        PostInit();
    }

    public static DRArea DeserializeDRArea(ByteBuf _buf)
    {
        return new Put.DRArea(_buf);
    }

    /// <summary>
    /// 区域Id
    /// </summary>
    public int Id { get; private set; }
    /// <summary>
    /// 名称
    /// </summary>
    public string Name { get; private set; }
    /// <summary>
    /// 场景Id
    /// </summary>
    public int SceneId { get; private set; }

    public const int __ID__ = 642606618;
    public override int GetTypeId() => __ID__;

    public  void Resolve(Dictionary<string, object> _tables)
    {
        PostResolve();
    }

    public  void TranslateText(System.Func<string, string, string> translator)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "Id:" + Id + ","
        + "Name:" + Name + ","
        + "SceneId:" + SceneId + ","
        + "}";
    }
    
    partial void PostInit();
    partial void PostResolve();
}

}
