//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Hotfix.Bright.Serialization;
using System.Collections.Generic;



namespace Hotfix.Model.Put
{

public sealed partial class DRDefaultSite :  Bright.Config.BeanBase 
{
    public DRDefaultSite(ByteBuf _buf) 
    {
        SiteID = _buf.ReadInt();
        AreaID = _buf.ReadInt();
        {int n = System.Math.Min(_buf.ReadSize(), _buf.Size);StaffList = new System.Collections.Generic.List<int>(n);for(var i = 0 ; i < n ; i++) { int _e;  _e = _buf.ReadInt(); StaffList.Add(_e);}}
        PostInit();
    }

    public static DRDefaultSite DeserializeDRDefaultSite(ByteBuf _buf)
    {
        return new Put.DRDefaultSite(_buf);
    }

    /// <summary>
    /// 站点ID
    /// </summary>
    public int SiteID { get; private set; }
    /// <summary>
    /// 所属区域
    /// </summary>
    public int AreaID { get; private set; }
    /// <summary>
    /// 初始员工
    /// </summary>
    public System.Collections.Generic.List<int> StaffList { get; private set; }

    public const int __ID__ = -1256676613;
    public override int GetTypeId() => __ID__;

    public  void Resolve(Dictionary<string, object> _tables)
    {
        PostResolve();
    }

    public  void TranslateText(System.Func<string, string, string> translator)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "SiteID:" + SiteID + ","
        + "AreaID:" + AreaID + ","
        + "StaffList:" + Bright.Common.StringUtil.CollectionToString(StaffList) + ","
        + "}";
    }
    
    partial void PostInit();
    partial void PostResolve();
}

}
