//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Hotfix.Bright.Serialization;
using System.Collections.Generic;



namespace Hotfix.Model.Put
{

public sealed partial class DRSkill :  Bright.Config.BeanBase 
{
    public DRSkill(ByteBuf _buf) 
    {
        ID = _buf.ReadInt();
        Name = _buf.ReadString();
        Desc = _buf.ReadString();
        Icon = _buf.ReadString();
        PostInit();
    }

    public static DRSkill DeserializeDRSkill(ByteBuf _buf)
    {
        return new Put.DRSkill(_buf);
    }

    /// <summary>
    /// 技能ID
    /// </summary>
    public int ID { get; private set; }
    /// <summary>
    /// 技能名称
    /// </summary>
    public string Name { get; private set; }
    /// <summary>
    /// 技能描述
    /// </summary>
    public string Desc { get; private set; }
    /// <summary>
    /// 技能图标
    /// </summary>
    public string Icon { get; private set; }

    public const int __ID__ = -1537612188;
    public override int GetTypeId() => __ID__;

    public  void Resolve(Dictionary<string, object> _tables)
    {
        PostResolve();
    }

    public  void TranslateText(System.Func<string, string, string> translator)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "ID:" + ID + ","
        + "Name:" + Name + ","
        + "Desc:" + Desc + ","
        + "Icon:" + Icon + ","
        + "}";
    }
    
    partial void PostInit();
    partial void PostResolve();
}

}
