//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Hotfix.Bright.Serialization;
using System.Collections.Generic;



namespace Hotfix.Model.Put
{

public sealed partial class DRStaff :  Bright.Config.BeanBase 
{
    public DRStaff(ByteBuf _buf) 
    {
        Id = _buf.ReadInt();
        Name = _buf.ReadString();
        Info = _buf.ReadString();
        Desc = _buf.ReadString();
        StaffPro = _buf.ReadInt();
        Speed = _buf.ReadInt();
        SpeedA = _buf.ReadFloat();
        SpeedB = _buf.ReadFloat();
        MoveSpeed = _buf.ReadFloat();
        MoveA = _buf.ReadFloat();
        MoveB = _buf.ReadFloat();
        AreaProfit = _buf.ReadInt();
        ManagerProfit = _buf.ReadInt();
        Social = _buf.ReadInt();
        AssetName = _buf.ReadString();
        Icon = _buf.ReadString();
        PostInit();
    }

    public static DRStaff DeserializeDRStaff(ByteBuf _buf)
    {
        return new Put.DRStaff(_buf);
    }

    /// <summary>
    /// 员工编号
    /// </summary>
    public int Id { get; private set; }
    /// <summary>
    /// 清洁工
    /// </summary>
    public string Name { get; private set; }
    /// <summary>
    /// 介绍信息
    /// </summary>
    public string Info { get; private set; }
    /// <summary>
    /// 详细描述
    /// </summary>
    public string Desc { get; private set; }
    /// <summary>
    /// 员工职业
    /// </summary>
    public int StaffPro { get; private set; }
    /// <summary>
    /// 基础清洁速度(s)<br/>1200-2000ms
    /// </summary>
    public int Speed { get; private set; }
    /// <summary>
    /// 速度成长A
    /// </summary>
    public float SpeedA { get; private set; }
    /// <summary>
    /// 速度成长B
    /// </summary>
    public float SpeedB { get; private set; }
    /// <summary>
    /// 基础移动速度<br/>0.85-1.5m/s
    /// </summary>
    public float MoveSpeed { get; private set; }
    /// <summary>
    /// 速度成长A
    /// </summary>
    public float MoveA { get; private set; }
    /// <summary>
    /// 速度成长B
    /// </summary>
    public float MoveB { get; private set; }
    /// <summary>
    /// 身体指数（站点收益）<br/>0-100<br/>1，1
    /// </summary>
    public int AreaProfit { get; private set; }
    /// <summary>
    /// 学识指数（个人收益）<br/>0-100<br/>0.2，0.3
    /// </summary>
    public int ManagerProfit { get; private set; }
    /// <summary>
    /// 社交指数（特殊事件）<br/>0-100<br/>-0.2，0.15
    /// </summary>
    public int Social { get; private set; }
    /// <summary>
    /// 地图图标<br/>顶视
    /// </summary>
    public string AssetName { get; private set; }
    /// <summary>
    /// 工卡图标
    /// </summary>
    public string Icon { get; private set; }

    public const int __ID__ = -1537351949;
    public override int GetTypeId() => __ID__;

    public  void Resolve(Dictionary<string, object> _tables)
    {
        PostResolve();
    }

    public  void TranslateText(System.Func<string, string, string> translator)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "Id:" + Id + ","
        + "Name:" + Name + ","
        + "Info:" + Info + ","
        + "Desc:" + Desc + ","
        + "StaffPro:" + StaffPro + ","
        + "Speed:" + Speed + ","
        + "SpeedA:" + SpeedA + ","
        + "SpeedB:" + SpeedB + ","
        + "MoveSpeed:" + MoveSpeed + ","
        + "MoveA:" + MoveA + ","
        + "MoveB:" + MoveB + ","
        + "AreaProfit:" + AreaProfit + ","
        + "ManagerProfit:" + ManagerProfit + ","
        + "Social:" + Social + ","
        + "AssetName:" + AssetName + ","
        + "Icon:" + Icon + ","
        + "}";
    }
    
    partial void PostInit();
    partial void PostResolve();
}

}
