//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Hotfix.Bright.Serialization;
using System.Collections.Generic;



namespace Hotfix.Model.Put
{

public sealed partial class DRStaffLevelUp :  Bright.Config.BeanBase 
{
    public DRStaffLevelUp(ByteBuf _buf) 
    {
        Level = _buf.ReadInt();
        CostSite = _buf.ReadInt();
        CostSalary = _buf.ReadInt();
        NewSkill = _buf.ReadInt();
        PostInit();
    }

    public static DRStaffLevelUp DeserializeDRStaffLevelUp(ByteBuf _buf)
    {
        return new Put.DRStaffLevelUp(_buf);
    }

    /// <summary>
    /// 等级
    /// </summary>
    public int Level { get; private set; }
    /// <summary>
    /// 站点资金
    /// </summary>
    public int CostSite { get; private set; }
    /// <summary>
    /// 工资
    /// </summary>
    public int CostSalary { get; private set; }
    /// <summary>
    /// 新加技能
    /// </summary>
    public int NewSkill { get; private set; }

    public const int __ID__ = 1879795404;
    public override int GetTypeId() => __ID__;

    public  void Resolve(Dictionary<string, object> _tables)
    {
        PostResolve();
    }

    public  void TranslateText(System.Func<string, string, string> translator)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "Level:" + Level + ","
        + "CostSite:" + CostSite + ","
        + "CostSalary:" + CostSalary + ","
        + "NewSkill:" + NewSkill + ","
        + "}";
    }
    
    partial void PostInit();
    partial void PostResolve();
}

}
