//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Hotfix.Bright.Serialization;
using System.Collections.Generic;

namespace Hotfix.Model.Put
{
   
public partial class TbItem
{
    private readonly Dictionary<int, Put.DRItem> _dataMap;
    private readonly List<Put.DRItem> _dataList;
    
    public TbItem(ByteBuf _buf)
    {
        _dataMap = new Dictionary<int, Put.DRItem>();
        _dataList = new List<Put.DRItem>();
        
        for(int n = _buf.ReadSize() ; n > 0 ; --n)
        {
            Put.DRItem _v;
            _v = Put.DRItem.DeserializeDRItem(_buf);
            _dataList.Add(_v);
            _dataMap.Add(_v.ID, _v);
        }
        PostInit();
    }

    public Dictionary<int, Put.DRItem> DataMap => _dataMap;
    public List<Put.DRItem> DataList => _dataList;

    public Put.DRItem GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public Put.DRItem Get(int key) => _dataMap[key];
    public Put.DRItem this[int key] => _dataMap[key];

    public void Resolve(Dictionary<string, object> _tables)
    {
        for(int i = 0 ; i < _dataList.Count ; i++)
        {
            _dataList[i].Resolve(_tables);
        }
        PostResolve();
    }

    public void TranslateText(System.Func<string, string, string> translator)
    {
        for(int i = 0 ; i < _dataList.Count ; i++)
        {
            _dataList[i].TranslateText(translator);
        }
    }
    
    partial void PostInit();
    partial void PostResolve();
}

}