//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Hotfix.Bright.Serialization;
using System.Collections.Generic;



namespace Hotfix.Model.SanXiao
{

public sealed partial class DRBlockUnit :  Bright.Config.BeanBase 
{
    public DRBlockUnit(ByteBuf _buf) 
    {
        ID = _buf.ReadInt();
        Image = _buf.ReadString();
        BlockType = _buf.ReadInt();
        CombineCheck = _buf.ReadInt();
        CombineE3 = _buf.ReadInt();
        CombineE4 = _buf.ReadInt();
        CombineE5 = _buf.ReadInt();
        CombineR59 = _buf.ReadInt();
        CombineL9 = _buf.ReadInt();
        SkillId = _buf.ReadInt();
        PostInit();
    }

    public static DRBlockUnit DeserializeDRBlockUnit(ByteBuf _buf)
    {
        return new SanXiao.DRBlockUnit(_buf);
    }

    /// <summary>
    /// ID
    /// </summary>
    public int ID { get; private set; }
    /// <summary>
    /// 图片名
    /// </summary>
    public string Image { get; private set; }
    /// <summary>
    /// 方块类型
    /// </summary>
    public int BlockType { get; private set; }
    /// <summary>
    /// 合成检查
    /// </summary>
    public int CombineCheck { get; private set; }
    /// <summary>
    /// 三合生成结果
    /// </summary>
    public int CombineE3 { get; private set; }
    /// <summary>
    /// 四合生成结果<br/>行/列
    /// </summary>
    public int CombineE4 { get; private set; }
    /// <summary>
    /// 五合生成结果<br/>3*3
    /// </summary>
    public int CombineE5 { get; private set; }
    /// <summary>
    /// 5＞ ≥9合生成结果<br/>菱形
    /// </summary>
    public int CombineR59 { get; private set; }
    /// <summary>
    /// &gt;9合生成结果<br/>消除同色
    /// </summary>
    public int CombineL9 { get; private set; }
    /// <summary>
    /// 技能
    /// </summary>
    public int SkillId { get; private set; }

    public const int __ID__ = 287467028;
    public override int GetTypeId() => __ID__;

    public  void Resolve(Dictionary<string, object> _tables)
    {
        PostResolve();
    }

    public  void TranslateText(System.Func<string, string, string> translator)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "ID:" + ID + ","
        + "Image:" + Image + ","
        + "BlockType:" + BlockType + ","
        + "CombineCheck:" + CombineCheck + ","
        + "CombineE3:" + CombineE3 + ","
        + "CombineE4:" + CombineE4 + ","
        + "CombineE5:" + CombineE5 + ","
        + "CombineR59:" + CombineR59 + ","
        + "CombineL9:" + CombineL9 + ","
        + "SkillId:" + SkillId + ","
        + "}";
    }
    
    partial void PostInit();
    partial void PostResolve();
}

}
