//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Hotfix.Bright.Serialization;
using System.Collections.Generic;



namespace Hotfix.Model.SanXiao
{

public sealed partial class DRHeroUnit :  Bright.Config.BeanBase 
{
    public DRHeroUnit(ByteBuf _buf) 
    {
        ID = _buf.ReadInt();
        Name = _buf.ReadString();
        {int n = System.Math.Min(_buf.ReadSize(), _buf.Size);SkillIds = new System.Collections.Generic.List<int>(n);for(var i = 0 ; i < n ; i++) { int _e;  _e = _buf.ReadInt(); SkillIds.Add(_e);}}
        CatIcon = _buf.ReadString();
        PostInit();
    }

    public static DRHeroUnit DeserializeDRHeroUnit(ByteBuf _buf)
    {
        return new SanXiao.DRHeroUnit(_buf);
    }

    /// <summary>
    /// ID
    /// </summary>
    public int ID { get; private set; }
    /// <summary>
    /// 名称
    /// </summary>
    public string Name { get; private set; }
    /// <summary>
    /// 技能Id
    /// </summary>
    public System.Collections.Generic.List<int> SkillIds { get; private set; }
    /// <summary>
    /// 对应的块
    /// </summary>
    public string CatIcon { get; private set; }

    public const int __ID__ = 1994642907;
    public override int GetTypeId() => __ID__;

    public  void Resolve(Dictionary<string, object> _tables)
    {
        PostResolve();
    }

    public  void TranslateText(System.Func<string, string, string> translator)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "ID:" + ID + ","
        + "Name:" + Name + ","
        + "SkillIds:" + Bright.Common.StringUtil.CollectionToString(SkillIds) + ","
        + "CatIcon:" + CatIcon + ","
        + "}";
    }
    
    partial void PostInit();
    partial void PostResolve();
}

}
