//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Hotfix.Bright.Serialization;
using System.Collections.Generic;



namespace Hotfix.Model.SanXiao
{

public sealed partial class DRLevelTheme :  Bright.Config.BeanBase 
{
    public DRLevelTheme(ByteBuf _buf) 
    {
        ID = _buf.ReadInt();
        Name = _buf.ReadString();
        Desc = _buf.ReadString();
        {int n = System.Math.Min(_buf.ReadSize(), _buf.Size);Item = new System.Collections.Generic.List<int>(n);for(var i = 0 ; i < n ; i++) { int _e;  _e = _buf.ReadInt(); Item.Add(_e);}}
        PostInit();
    }

    public static DRLevelTheme DeserializeDRLevelTheme(ByteBuf _buf)
    {
        return new SanXiao.DRLevelTheme(_buf);
    }

    /// <summary>
    /// ID
    /// </summary>
    public int ID { get; private set; }
    /// <summary>
    /// 名称
    /// </summary>
    public string Name { get; private set; }
    /// <summary>
    /// 描述
    /// </summary>
    public string Desc { get; private set; }
    /// <summary>
    /// 道具组
    /// </summary>
    public System.Collections.Generic.List<int> Item { get; private set; }

    public const int __ID__ = -759011678;
    public override int GetTypeId() => __ID__;

    public  void Resolve(Dictionary<string, object> _tables)
    {
        PostResolve();
    }

    public  void TranslateText(System.Func<string, string, string> translator)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "ID:" + ID + ","
        + "Name:" + Name + ","
        + "Desc:" + Desc + ","
        + "Item:" + Bright.Common.StringUtil.CollectionToString(Item) + ","
        + "}";
    }
    
    partial void PostInit();
    partial void PostResolve();
}

}
