//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Hotfix.Bright.Serialization;
using System.Collections.Generic;



namespace Hotfix.Model.SanXiao
{

public sealed partial class DRSanXiaoBuff :  Bright.Config.BeanBase 
{
    public DRSanXiaoBuff(ByteBuf _buf) 
    {
        ID = _buf.ReadInt();
        Name = _buf.ReadString();
        CanMove = _buf.ReadBool();
        NeedRemoveBlock = _buf.ReadBool();
        CanCombine = _buf.ReadBool();
        CanBeEffectedByHero = _buf.ReadBool();
        EliminateCount = _buf.ReadInt();
        View = _buf.ReadString();
        PostInit();
    }

    public static DRSanXiaoBuff DeserializeDRSanXiaoBuff(ByteBuf _buf)
    {
        return new SanXiao.DRSanXiaoBuff(_buf);
    }

    /// <summary>
    /// Buff的ID
    /// </summary>
    public int ID { get; private set; }
    /// <summary>
    /// 名称
    /// </summary>
    public string Name { get; private set; }
    /// <summary>
    /// 能否移动
    /// </summary>
    public bool CanMove { get; private set; }
    /// <summary>
    /// 消除时候是否移除方块
    /// </summary>
    public bool NeedRemoveBlock { get; private set; }
    /// <summary>
    /// 能否参加合成
    /// </summary>
    public bool CanCombine { get; private set; }
    /// <summary>
    /// 能否被猫咪影响
    /// </summary>
    public bool CanBeEffectedByHero { get; private set; }
    /// <summary>
    /// 能被消除的次数
    /// </summary>
    public int EliminateCount { get; private set; }
    /// <summary>
    /// buff表现
    /// </summary>
    public string View { get; private set; }

    public const int __ID__ = 1440871797;
    public override int GetTypeId() => __ID__;

    public  void Resolve(Dictionary<string, object> _tables)
    {
        PostResolve();
    }

    public  void TranslateText(System.Func<string, string, string> translator)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "ID:" + ID + ","
        + "Name:" + Name + ","
        + "CanMove:" + CanMove + ","
        + "NeedRemoveBlock:" + NeedRemoveBlock + ","
        + "CanCombine:" + CanCombine + ","
        + "CanBeEffectedByHero:" + CanBeEffectedByHero + ","
        + "EliminateCount:" + EliminateCount + ","
        + "View:" + View + ","
        + "}";
    }
    
    partial void PostInit();
    partial void PostResolve();
}

}
