//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Hotfix.Bright.Serialization;
using System.Collections.Generic;

namespace Hotfix.Model.SanXiao
{
   
public partial class TbSanXiaoSkill
{
    private readonly Dictionary<int, SanXiao.DRSanXiaoSkill> _dataMap;
    private readonly List<SanXiao.DRSanXiaoSkill> _dataList;
    
    public TbSanXiaoSkill(ByteBuf _buf)
    {
        _dataMap = new Dictionary<int, SanXiao.DRSanXiaoSkill>();
        _dataList = new List<SanXiao.DRSanXiaoSkill>();
        
        for(int n = _buf.ReadSize() ; n > 0 ; --n)
        {
            SanXiao.DRSanXiaoSkill _v;
            _v = SanXiao.DRSanXiaoSkill.DeserializeDRSanXiaoSkill(_buf);
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
        PostInit();
    }

    public Dictionary<int, SanXiao.DRSanXiaoSkill> DataMap => _dataMap;
    public List<SanXiao.DRSanXiaoSkill> DataList => _dataList;

    public SanXiao.DRSanXiaoSkill GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public SanXiao.DRSanXiaoSkill Get(int key) => _dataMap[key];
    public SanXiao.DRSanXiaoSkill this[int key] => _dataMap[key];

    public void Resolve(Dictionary<string, object> _tables)
    {
        for(int i = 0 ; i < _dataList.Count ; i++)
        {
            _dataList[i].Resolve(_tables);
        }
        PostResolve();
    }

    public void TranslateText(System.Func<string, string, string> translator)
    {
        for(int i = 0 ; i < _dataList.Count ; i++)
        {
            _dataList[i].TranslateText(translator);
        }
    }
    
    partial void PostInit();
    partial void PostResolve();
}

}