//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Hotfix.Bright.Serialization;
using System.Collections.Generic;

namespace Hotfix.Model.SanXiao
{
   
public partial class TbSanXiaoBuff
{
    private readonly Dictionary<int, SanXiao.DRSanXiaoBuff> _dataMap;
    private readonly List<SanXiao.DRSanXiaoBuff> _dataList;
    
    public TbSanXiaoBuff(ByteBuf _buf)
    {
        _dataMap = new Dictionary<int, SanXiao.DRSanXiaoBuff>();
        _dataList = new List<SanXiao.DRSanXiaoBuff>();
        
        for(int n = _buf.ReadSize() ; n > 0 ; --n)
        {
            SanXiao.DRSanXiaoBuff _v;
            _v = SanXiao.DRSanXiaoBuff.DeserializeDRSanXiaoBuff(_buf);
            _dataList.Add(_v);
            _dataMap.Add(_v.ID, _v);
        }
        PostInit();
    }

    public Dictionary<int, SanXiao.DRSanXiaoBuff> DataMap => _dataMap;
    public List<SanXiao.DRSanXiaoBuff> DataList => _dataList;

    public SanXiao.DRSanXiaoBuff GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public SanXiao.DRSanXiaoBuff Get(int key) => _dataMap[key];
    public SanXiao.DRSanXiaoBuff this[int key] => _dataMap[key];

    public void Resolve(Dictionary<string, object> _tables)
    {
        for(int i = 0 ; i < _dataList.Count ; i++)
        {
            _dataList[i].Resolve(_tables);
        }
        PostResolve();
    }

    public void TranslateText(System.Func<string, string, string> translator)
    {
        for(int i = 0 ; i < _dataList.Count ; i++)
        {
            _dataList[i].TranslateText(translator);
        }
    }
    
    partial void PostInit();
    partial void PostResolve();
}

}